package ir

import (
	"fmt"
	"strings"
)

// GenerateX86 translates TAC IR to x86-64 assembly string
// This is a simple, linear, unoptimized translation
func GenerateX86(code Code) string {
	var output strings.Builder

	// Assembly header
	output.WriteString("# Generated by CTDS Compiler - Simple Linear Translation\n")
	output.WriteString("# Target: x86-64 (System V ABI)\n")
	output.WriteString("\n")

	// Data section for globals
	output.WriteString(".section .data\n")
	output.WriteString(".align 8\n")
	output.WriteString("globals:\n")
	output.WriteString("    .space 8000  # Global variables space\n")
	output.WriteString("\n")

	// Text section
	output.WriteString(".section .text\n")
	output.WriteString(".globl main\n")
	output.WriteString("\n")

	// Translate each instruction linearly
	for _, instr := range code {
		output.WriteString(translateInstruction(instr))
	}

	return output.String()
}

// translateInstruction converts a single TAC instruction to x86-64
func translateInstruction(instr Instr) string {
	var out strings.Builder

	switch instr.Op {

	case OpLabel:
		// Label: just emit the label
		if instr.S != "" {
			out.WriteString(fmt.Sprintf("%s:\n", instr.S))
			// If it's a function label (not Lxx), add stack frame setup
			if !strings.HasPrefix(instr.S, "L") {
				out.WriteString("    push rbp\n")
				out.WriteString("    mov rbp, rsp\n")
				out.WriteString("    sub rsp, 512  # Fixed frame size\n")
			}
		}

	case OpCopy:
		// D = A
		out.WriteString(fmt.Sprintf("    # Copy %s -> %s\n", instr.A.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(storeFromReg("rax", instr.D))

	case OpAdd:
		// D = A + B
		out.WriteString(fmt.Sprintf("    # Add %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    add rax, rbx\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpSub:
		// D = A - B
		out.WriteString(fmt.Sprintf("    # Sub %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    sub rax, rbx\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpMul:
		// D = A * B
		out.WriteString(fmt.Sprintf("    # Mul %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    imul rax, rbx\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpDiv:
		// D = A / B
		out.WriteString(fmt.Sprintf("    # Div %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    cqo\n") // Sign extend rax to rdx:rax
		out.WriteString("    idiv rbx\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpRem:
		// D = A % B
		out.WriteString(fmt.Sprintf("    # Rem %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    cqo\n")
		out.WriteString("    idiv rbx\n")
		out.WriteString("    mov rax, rdx\n") // Remainder in rdx
		out.WriteString(storeFromReg("rax", instr.D))

	case OpLT:
		// D = A < B
		out.WriteString(fmt.Sprintf("    # LT %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    cmp rax, rbx\n")
		out.WriteString("    setl al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpGT:
		// D = A > B
		out.WriteString(fmt.Sprintf("    # GT %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    cmp rax, rbx\n")
		out.WriteString("    setg al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpEQ:
		// D = A == B
		out.WriteString(fmt.Sprintf("    # EQ %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString(loadToReg(instr.B, "rbx"))
		out.WriteString("    cmp rax, rbx\n")
		out.WriteString("    sete al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpNot:
		// D = !A
		out.WriteString(fmt.Sprintf("    # Not %s -> %s\n", instr.A.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString("    test rax, rax\n")
		out.WriteString("    sete al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D))

	case OpIfZ:
		// if A == 0 goto label
		out.WriteString(fmt.Sprintf("    # IfZ %s -> %s\n", instr.A.String(), instr.S))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString("    test rax, rax\n")
		out.WriteString(fmt.Sprintf("    jz %s\n", instr.S))

	case OpGoto:
		// goto label
		out.WriteString(fmt.Sprintf("    # Goto %s\n", instr.S))
		out.WriteString(fmt.Sprintf("    jmp %s\n", instr.S))

	case OpParam:
		// Push parameter onto stack
		out.WriteString(fmt.Sprintf("    # Param %s\n", instr.A.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString("    push rax\n")

	case OpCall:
		// Call function with K parameters
		out.WriteString(fmt.Sprintf("    # Call %s, arity=%d\n", instr.S, instr.K))

		// Pop parameters from stack into argument registers
		// First 6 go into registers: rdi, rsi, rdx, rcx, r8, r9
		argRegs := []string{"rdi", "rsi", "rdx", "rcx", "r8", "r9"}

		// Pop in reverse order (last pushed = first arg)
		for i := instr.K - 1; i >= 0; i-- {
			out.WriteString("    pop rax\n")
			if i < len(argRegs) {
				out.WriteString(fmt.Sprintf("    mov %s, rax\n", argRegs[i]))
			} else {
				// Beyond 6th argument, push back onto stack
				out.WriteString("    push rax\n")
			}
		}

		// Align stack and call
		out.WriteString("    mov r10, rsp\n")
		out.WriteString("    and rsp, -16\n")
		out.WriteString(fmt.Sprintf("    call %s\n", instr.S))
		out.WriteString("    mov rsp, r10\n")

		// Clean up stack args (beyond 6th)
		if instr.K > 6 {
			stackArgs := instr.K - 6
			out.WriteString(fmt.Sprintf("    add rsp, %d\n", stackArgs*8))
		}

		// Store return value
		out.WriteString(storeFromReg("rax", instr.D))

	case OpRet:
		// Return from void function
		out.WriteString("    # Return (void)\n")
		out.WriteString("    mov rsp, rbp\n")
		out.WriteString("    pop rbp\n")
		out.WriteString("    ret\n")

	case OpRetV:
		// Return with value
		out.WriteString(fmt.Sprintf("    # Return %s\n", instr.A.String()))
		out.WriteString(loadToReg(instr.A, "rax"))
		out.WriteString("    mov rsp, rbp\n")
		out.WriteString("    pop rbp\n")
		out.WriteString("    ret\n")
	}

	return out.String()
}

// loadToReg generates code to load an address into a register
func loadToReg(addr Addr, reg string) string {
	switch addr.Kind {
	case Literal:
		// Immediate value
		return fmt.Sprintf("    mov %s, %d\n", reg, addr.Value)

	case Global:
		// Global variable at offset in data section
		return fmt.Sprintf("    mov %s, [globals + %d]\n", reg, addr.Value*8)

	case Offset:
		if addr.Value < 0 {
			// Function parameter (negative offset)
			// Parameters are at rbp+16, rbp+24, etc.
			offset := (-addr.Value-1)*8 + 16
			return fmt.Sprintf("    mov %s, [rbp + %d]\n", reg, offset)
		} else {
			// Local variable/temporary (positive offset)
			// Locals are at rbp-8, rbp-16, etc.
			return fmt.Sprintf("    mov %s, [rbp - %d]\n", reg, addr.Value*8)
		}
	}

	return ""
}

// storeFromReg generates code to store a register into an address
func storeFromReg(reg string, addr Addr) string {
	switch addr.Kind {
	case Literal:
		// Cannot store to literal
		return "    # ERROR: Cannot store to literal\n"

	case Global:
		// Global variable
		return fmt.Sprintf("    mov [globals + %d], %s\n", addr.Value*8, reg)

	case Offset:
		if addr.Value < 0 {
			// Function parameter
			offset := (-addr.Value-1)*8 + 16
			return fmt.Sprintf("    mov [rbp + %d], %s\n", offset, reg)
		} else {
			// Local variable/temporary
			return fmt.Sprintf("    mov [rbp - %d], %s\n", addr.Value*8, reg)
		}
	}

	return ""
}
