package ir

import (
	"fmt"
	"strings"
)

// funcContext carries per-function stack layout data for code generation.
type funcContext struct {
	localBytes int // space for locals/temps (positive offsets)
	spillSlots int // how many register params are spilled (0..6)
	totalFrame int // aligned frame size (locals + spills), multiple of 16
	paramCount int // total params observed (incl. >6 stack params)
	instrCount int // number of non-label instructions (0 => likely extern)
}

// analyzeFunctions scans the IR and gathers stack requirements per function.
func analyzeFunctions(code Code) map[string]funcContext {
	ctxs := make(map[string]funcContext)

	var cur string
	maxLocalSlots := 0
	maxParam := 0
	curCount := 0

	flush := func() {
		if cur == "" {
			return
		}
		localBytes := maxLocalSlots * 8
		spillSlots := min(maxParam, 6)
		spillBytes := spillSlots * 8
		total := localBytes + spillBytes
		if total%16 != 0 {
			total += 16 - (total % 16)
		}
		ctxs[cur] = funcContext{
			localBytes: localBytes,
			spillSlots: spillSlots,
			totalFrame: total,
			paramCount: maxParam,
			instrCount: curCount,
		}
	}

	for _, instr := range code {
		if instr.Op == OpLabel && instr.S != "" && !strings.HasPrefix(instr.S, "L") {
			flush()
			cur = instr.S
			maxLocalSlots = 0
			maxParam = 0
			curCount = 0
			continue
		}
		if cur != "" && instr.Op != OpLabel {
			curCount++
		}
		for _, addr := range []Addr{instr.D, instr.A, instr.B} {
			if addr.Kind != Offset {
				continue
			}
			if addr.Value >= 0 {
				slots := addr.Value + 1
				if slots > maxLocalSlots {
					maxLocalSlots = slots
				}
			}
			if addr.Value < 0 {
				idx := -addr.Value
				if idx > maxParam {
					maxParam = idx
				}
			}
		}
	}
	flush()
	return ctxs
}

// GenerateX86 translates TAC IR to x86-64 assembly string
// This is a simple, linear, unoptimized translation
func GenerateX86(code Code) string {
	var output strings.Builder
	funcInfo := analyzeFunctions(code)
	currentFunc := ""

	// Assembly header
	output.WriteString("# Generated by CTDS Compiler - Simple Linear Translation\n")
	output.WriteString("# Target: x86-64 (System V ABI)\n")
	output.WriteString(".intel_syntax noprefix\n")
	output.WriteString("\n")

	// Data section for globals
	output.WriteString(".section .data\n")
	output.WriteString(".align 8\n")
	output.WriteString("globals:\n")
	output.WriteString("    .space 8000  # Global variables space\n")
	output.WriteString("\n")

	// Text section
	output.WriteString(".section .text\n")
	output.WriteString(".globl main\n")
	output.WriteString("\n")

	// Translate each instruction linearly
	for _, instr := range code {
		if instr.Op == OpLabel && instr.S != "" && !strings.HasPrefix(instr.S, "L") {
			currentFunc = instr.S
		}
		ctx := funcInfo[currentFunc]
		output.WriteString(translateInstruction(instr, &ctx))
	}

	// Mark non-executable stack
	output.WriteString("\n.section .note.GNU-stack,\"\",@progbits\n")

	return output.String()
}

// translateInstruction converts a single TAC instruction to x86-64
func translateInstruction(instr Instr, ctx *funcContext) string {
	var out strings.Builder

	switch instr.Op {

	case OpLabel:
		// Label: just emit the label
		if instr.S != "" {
			// Skip emitting extern-only labels (no body)
			if !strings.HasPrefix(instr.S, "L") && ctx.instrCount == 0 {
				return ""
			}
			out.WriteString(fmt.Sprintf("%s:\n", instr.S))
			// If it's a function label (not Lxx), add stack frame setup
			if !strings.HasPrefix(instr.S, "L") {
				out.WriteString("    push rbp\n")
				out.WriteString("    mov rbp, rsp\n")
				if ctx.totalFrame > 0 {
					out.WriteString(fmt.Sprintf("    sub rsp, %d\n", ctx.totalFrame))
				}
				// Spill register parameters to frame slots for uniform access
				argRegs := []string{"rdi", "rsi", "rdx", "rcx", "r8", "r9"}
				for i := 0; i < ctx.spillSlots; i++ {
					offset := ctx.localBytes + (i+1)*8
					out.WriteString(fmt.Sprintf("    mov qword ptr [rbp - %d], %s\n", offset, argRegs[i]))
				}
			}
		}

	case OpCopy:
		// D = A
		out.WriteString(fmt.Sprintf("    # Copy %s -> %s\n", instr.A.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpAdd:
		// D = A + B
		out.WriteString(fmt.Sprintf("    # Add %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    add rax, rcx\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpSub:
		// D = A - B
		out.WriteString(fmt.Sprintf("    # Sub %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    sub rax, rcx\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpMul:
		// D = A * B
		out.WriteString(fmt.Sprintf("    # Mul %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    imul rax, rcx\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpDiv:
		// D = A / B
		out.WriteString(fmt.Sprintf("    # Div %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    cqo\n") // Sign extend rax to rdx:rax
		out.WriteString("    idiv rcx\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpRem:
		// D = A % B
		out.WriteString(fmt.Sprintf("    # Rem %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    cqo\n")
		out.WriteString("    idiv rcx\n")
		out.WriteString("    mov rax, rdx\n") // Remainder in rdx
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpLT:
		// D = A < B
		out.WriteString(fmt.Sprintf("    # LT %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    cmp rax, rcx\n")
		out.WriteString("    setl al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpGT:
		// D = A > B
		out.WriteString(fmt.Sprintf("    # GT %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    cmp rax, rcx\n")
		out.WriteString("    setg al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpEQ:
		// D = A == B
		out.WriteString(fmt.Sprintf("    # EQ %s, %s -> %s\n", instr.A.String(), instr.B.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString(loadToReg(instr.B, "rcx", ctx))
		out.WriteString("    cmp rax, rcx\n")
		out.WriteString("    sete al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpNot:
		// D = !A
		out.WriteString(fmt.Sprintf("    # Not %s -> %s\n", instr.A.String(), instr.D.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString("    test rax, rax\n")
		out.WriteString("    sete al\n")
		out.WriteString("    movzx rax, al\n")
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpIfZ:
		// if A == 0 goto label
		out.WriteString(fmt.Sprintf("    # IfZ %s -> %s\n", instr.A.String(), instr.S))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString("    test rax, rax\n")
		out.WriteString(fmt.Sprintf("    jz %s\n", instr.S))

	case OpGoto:
		// goto label
		out.WriteString(fmt.Sprintf("    # Goto %s\n", instr.S))
		out.WriteString(fmt.Sprintf("    jmp %s\n", instr.S))

	case OpParam:
		// Push parameter onto stack
		out.WriteString(fmt.Sprintf("    # Param %s\n", instr.A.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString("    push rax\n")

	case OpCall:
		// Call function with K parameters
		out.WriteString(fmt.Sprintf("    # Call %s, arity=%d\n", instr.S, instr.K))

		argRegs := []string{"rdi", "rsi", "rdx", "rcx", "r8", "r9"}

		// Base pointer to the temporary argument area (pushed by OpParam)
		out.WriteString("    lea r11, [rsp]\n")

		// Move first six arguments into registers (read from stacked params)
		limit := instr.K
		if limit > 6 {
			limit = 6
		}
		for i := 0; i < limit; i++ {
			offset := (instr.K - 1 - i) * 8
			out.WriteString(fmt.Sprintf("    mov %s, qword ptr [r11 + %d]\n", argRegs[i], offset))
		}

		// Push stack arguments (beyond 6) right-to-left
		for i := instr.K - 1; i >= 6; i-- {
			offset := (instr.K - 1 - i) * 8
			out.WriteString(fmt.Sprintf("    push qword ptr [r11 + %d]\n", offset))
		}

		// Align stack for call: ensure (rsp + 8) % 16 == 0
		out.WriteString("    mov rax, rsp\n")
		out.WriteString("    add rax, 8\n")
		out.WriteString("    and rax, 15\n")
		out.WriteString("    neg rax\n")
		out.WriteString("    and rax, 15\n")
		out.WriteString("    sub rsp, rax\n")

		out.WriteString(fmt.Sprintf("    call %s\n", instr.S))

		// Clean argument area (OpParam pushes + any stack args we added + padding)
		out.WriteString(fmt.Sprintf("    add rsp, %d\n", instr.K*8))
		if instr.K > 6 {
			stackArgs := instr.K - 6
			out.WriteString(fmt.Sprintf("    add rsp, %d\n", stackArgs*8))
		}
		out.WriteString("    add rsp, rax\n")

		// Store return value
		out.WriteString(storeFromReg("rax", instr.D, ctx))

	case OpRet:
		// Return from void function
		out.WriteString("    # Return (void)\n")
		out.WriteString("    mov rsp, rbp\n")
		out.WriteString("    pop rbp\n")
		out.WriteString("    ret\n")

	case OpRetV:
		// Return with value
		out.WriteString(fmt.Sprintf("    # Return %s\n", instr.A.String()))
		out.WriteString(loadToReg(instr.A, "rax", ctx))
		out.WriteString("    mov rsp, rbp\n")
		out.WriteString("    pop rbp\n")
		out.WriteString("    ret\n")
	}

	return out.String()
}

// loadToReg generates code to load an address into a register
func loadToReg(addr Addr, reg string, ctx *funcContext) string {
	switch addr.Kind {
	case Literal:
		// Immediate value
		return fmt.Sprintf("    mov %s, %d\n", reg, addr.Value)

	case Global:
		// Global variable at offset in data section
		return fmt.Sprintf("    mov %s, [globals + %d]\n", reg, addr.Value*8)

	case Offset:
		if addr.Value < 0 {
			// Function parameter (negative offset)
			idx := -addr.Value - 1
			if idx < ctx.spillSlots {
				offset := ctx.localBytes + (idx+1)*8
				return fmt.Sprintf("    mov %s, [rbp - %d]\n", reg, offset)
			}
			// Beyond 6th parameter: still lives in caller stack above rbp
			offset := (idx-6)*8 + 16
			return fmt.Sprintf("    mov %s, [rbp + %d]\n", reg, offset)
		} else {
			// Local variable/temporary (positive offset)
			slot := addr.Value + 1
			return fmt.Sprintf("    mov %s, [rbp - %d]\n", reg, slot*8)
		}
	}

	return ""
}

// storeFromReg generates code to store a register into an address
func storeFromReg(reg string, addr Addr, ctx *funcContext) string {
	switch addr.Kind {
	case Literal:
		// Cannot store to literal
		return "    # ERROR: Cannot store to literal\n"

	case Global:
		// Global variable
		return fmt.Sprintf("    mov [globals + %d], %s\n", addr.Value*8, reg)

	case Offset:
		if addr.Value < 0 {
			// Function parameter
			idx := -addr.Value - 1
			if idx < ctx.spillSlots {
				offset := ctx.localBytes + (idx+1)*8
				return fmt.Sprintf("    mov [rbp - %d], %s\n", offset, reg)
			}
			offset := (idx-6)*8 + 16
			return fmt.Sprintf("    mov [rbp + %d], %s\n", offset, reg)
		} else {
			// Local variable/temporary
			slot := addr.Value + 1
			return fmt.Sprintf("    mov [rbp - %d], %s\n", slot*8, reg)
		}
	}

	return ""
}
